#로깅 관련
logging:
  file:
    name: logs/api-local3.log    #파일경로
    max-size: 500MB       #로그파일 최대 사이즈
    max-history: 10       #최대 보관 일수
  level:
    root: info            #기본 로깅레벨
    org.msa.item: debug   #해당 패키지 내에 로깅을 debug 레벨로 처리
    
#JPA
spring:
  config:
    import:
      - classpath:/config/datasource-local.yaml # jpa db연동 설정은 해당 path 에서 가져온다
 
#SpringDoc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html  #Swagger UI 경로
    operations-sorter: alpha  #함수 알파벳 순으로 정렬
    tags-sorter: alpha  #태그 알파벳 순으로 정렬
    disable-swagger-default-url: true  #기본 Swagger UI URL 비활성화
    display-query-params-without-oauth2: true  #OAuth2 없이 URL 쿼리 매개변수 표시	

#암복호화
token:
   expiration_time: 86400000
   secret: SECU100
   
# Eureka Server
eureka:
   instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} #인스턴스 id 값을 호스트명 + 랜덤포트 값 
      prefer-ip-address: true # 호스트이름이 아닌 ip주소를 이용해 유레카 서버에 등록할 것인지에 대한 여부
   client:
      register-with-eureka: true # 아이템 서비스는 유레카에 등록해야하니깐 true
      fetch-registry: true # 구동중인 마이크로서비스는 출력되어야 하니깐 true
      service-url:
         defaultZone: http://localhost:8761/eureka #유레카주소